id: P333F3F03
initial_creation_type: ocr
source_metadata:
  volumes:
    7d7a1c72b12943eb9ad8cc637ce70d1c:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: ཚོགས་ཀྱི་གཏམ།
      total_pages: 1144
      volume_number: 96
